"""empty message

Revision ID: a94294b693df
Revises: ca1a55011fbc
Create Date: 2021-01-03 14:44:33.032341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94294b693df'
down_revision = 'ca1a55011fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('member',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('card_ID', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('register_date', sa.DATE(), nullable=True),
    sa.Column('renewal_date', sa.DATE(), nullable=True),
    sa.Column('aggregate_amount', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('supplier',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.Column('level', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('goods',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('bar_code', sa.String(length=255), nullable=True),
    sa.Column('inventory', sa.INTEGER(), nullable=True),
    sa.Column('promotion_price', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('state', sa.SMALLINT(), nullable=True),
    sa.Column('limit_num', sa.INTEGER(), nullable=True),
    sa.Column('factory_ID', sa.String(length=255), nullable=True),
    sa.Column('supplier_ID', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['factory_ID'], ['factory.ID'], ),
    sa.ForeignKeyConstraint(['supplier_ID'], ['supplier.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('trade',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('member_ID', sa.String(length=255), nullable=True),
    sa.Column('staff_ID', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['member_ID'], ['member.ID'], ),
    sa.ForeignKeyConstraint(['staff_ID'], ['staff.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('entry',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('goods_ID', sa.String(length=255), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DATE(), nullable=True),
    sa.Column('state', sa.SMALLINT(), nullable=True),
    sa.Column('total_amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['goods_ID'], ['goods.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('sale',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('goods_ID', sa.String(length=255), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('total_amount', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['goods_ID'], ['goods.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('stock',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('goods_ID', sa.String(length=255), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('plan_time', sa.DATE(), nullable=True),
    sa.Column('state', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['goods_ID'], ['goods.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('sale')
    op.drop_table('entry')
    op.drop_table('trade')
    op.drop_table('goods')
    op.drop_table('supplier')
    op.drop_table('member')
    op.drop_table('factory')
    # ### end Alembic commands ###
