"""empty message

Revision ID: ca1a55011fbc
Revises: 
Create Date: 2021-01-03 14:34:15.109339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1a55011fbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('ID', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.DATETIME(), nullable=True),
    sa.Column('work_age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.add_column('account', sa.Column('authority', sa.SMALLINT(), nullable=True))
    op.add_column('account', sa.Column('staff_ID', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'account', 'staff', ['staff_ID'], ['ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'staff_ID')
    op.drop_column('account', 'authority')
    op.drop_table('staff')
    # ### end Alembic commands ###
